# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: cff-validator
'on':
  push:
    paths:
      - CITATION.cff
  pull_request:
    paths:
      - CITATION.cff
jobs:
  cff-validator:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dieghernan/cff-validator@v3
