# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: make
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  make:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo make install FORCE_INSTALL=true
      - run: make env lint test
  make-macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - run: sudo chown -R "$(whoami)" /usr/local
      - name: 'Update make and bash'
        run: brew install make bash
      - name: 'Add make to PATH'
        run: echo "/opt/homebrew/opt/make/libexec/gnubin" >> "$GITHUB_PATH"
      - run: sudo make install FORCE_INSTALL=true
      - run: make env lint test
